name: Deploy to Netlify
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build:storybook

      - name: Verify build output
        run: ls -la ./storybook-static

      - name: Deploy to Netlify
        run: cd storybook-static && netlify deploy --prod --dir=. --site=${{ secrets.NETLIFY_SITE_ID }}
        env:
          TOKEN: ${{ secrets.TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
