name: Publish
run-name: Publish by @${{ github.actor }}
on:
  pull_request:
    types: 
      - closed
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Force actions/checkout to get all commits and tags
          fetch-depth: 0
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@douro-ui'
      - name: "Install Dependencies"
        run: yarn install
      - name: "Run Lerna Version and Publish"
        # To enable authentication with lerna we must set the origin url for git with the token
        run: | 
          git remote set-url origin "https://${{secrets.GITHUB_TOKEN}}@github.com/Douro-ui/design-system.git"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          yarn lerna:version
          yarn lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}