name: Publish
run-name: Publish by @${{ github.actor }}
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4
        with:
          # Force actions/checkout to get all commits and tags
          fetch-depth: 0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the organization that owns the workflow file
          scope: '@douro-ui'
      - name: "Install Dependencies"
        run: yarn install
      - name: "Version and Publish"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          yarn lerna:version
          yarn lerna:build
          yarn lerna:publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
